"""Type stubs for `avplayer` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

class Player:
    id: str
    url: str
    def __init__(self, player_id: Any = ..., url: Any | None = ...) -> None: ...
    def load(self, url: Any) -> bool: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    def seek(self, seconds: Any) -> None: ...
    def duration(self) -> float: ...
    def current_time(self) -> float: ...
    def is_playing(self) -> bool: ...
    def set_volume(self, volume: Any) -> None: ...
    def set_rate(self, rate: Any) -> None: ...
    def on_progress(self, callback_id: Any, interval_ms: int = ...) -> None: ...
    def stop_progress(self) -> None: ...
    def on_end(self, callback_id: Any) -> None: ...
    def on_error(self, callback_id: Any) -> None: ...
    def on_status(self, callback_id: Any) -> None: ...
    def on_pip(self, callback_id: Any) -> None: ...
    def cleanup(self) -> None: ...

def load(url: Any) -> Any: ...

def play() -> Any: ...

def pause() -> Any: ...

def stop() -> Any: ...

def seek(seconds: Any) -> Any: ...

def duration() -> Any: ...

def current_time() -> Any: ...

def is_playing() -> bool: ...

def set_volume(volume: Any) -> None: ...

def set_rate(rate: Any) -> None: ...

def present_video() -> Any: ...

def on_progress(callback_id: Any, interval_ms: int = ...) -> Any: ...

def stop_progress() -> None: ...

def on_end(callback_id: Any) -> Any: ...

def cleanup() -> Any: ...

__all__ = ['Player', 'load', 'play', 'pause', 'stop', 'seek', 'duration', 'current_time', 'is_playing', 'set_volume', 'set_rate', 'present_video', 'on_progress', 'stop_progress', 'on_end', 'cleanup']
