"""Type stubs for `background` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def begin_task() -> Any: ...

def end_task() -> Any: ...

def remaining_time() -> Any: ...

def app_state() -> Any: ...

def start_keep_alive() -> Any: ...

def stop_keep_alive() -> None: ...

def schedule_refresh(identifier: Any, earliest_date: int = ...) -> Any: ...

def schedule_processing(identifier: Any, earliest_date: int = ..., requires_network: bool = ..., requires_charging: bool = ...) -> Any: ...

__all__ = ['begin_task', 'end_task', 'remaining_time', 'app_state', 'start_keep_alive', 'stop_keep_alive', 'schedule_refresh', 'schedule_processing']
