"""Type stubs for `bluetooth` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def state() -> Any: ...

def scan(duration: float = ...) -> Any: ...

def stop_scan() -> None: ...

def connect(uuid: Any) -> Any: ...

def disconnect(uuid: Any) -> Any: ...

def discover_services(uuid: Any) -> Any: ...

def read(peripheral_uuid: Any, service_uuid: Any, characteristic_uuid: Any) -> Any: ...

def write(peripheral_uuid: Any, service_uuid: Any, characteristic_uuid: Any, base64_data: Any) -> Any: ...

__all__ = ['state', 'scan', 'stop_scan', 'connect', 'disconnect', 'discover_services', 'read', 'write']
