"""Type stubs for `calendar_events` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def authorization_status() -> Any: ...

def request_access() -> Any: ...

def get_calendars() -> Any: ...

def get_events(start: Any, end: Any, calendar_id: Any | None = ...) -> Any: ...

def create_event(title: Any, start: Any, end: Any, *, notes: Any | None = ..., location: Any | None = ..., calendar_id: Any | None = ..., all_day: bool = ...) -> Any: ...

def delete_event(event_id: Any) -> None: ...

def request_reminder_access() -> Any: ...

def get_reminders() -> Any: ...

def create_reminder(title: Any, notes: Any | None = ..., due_timestamp: Any | None = ...) -> Any: ...

def complete_reminder(reminder_id: Any) -> Any: ...

def delete_reminder(reminder_id: Any) -> None: ...

__all__ = ['authorization_status', 'request_access', 'get_calendars', 'get_events', 'create_event', 'delete_event', 'request_reminder_access', 'get_reminders', 'create_reminder', 'complete_reminder', 'delete_reminder']
