"""Type stubs for `console` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def alert(title: str, message: str = ..., *, button1: str = ..., button2: str = ..., button3: str = ..., hide_cancel_button: bool = ...) -> int: ...

def hud_alert(message: str, icon: str = ..., duration: float = ...) -> None: ...

def input_alert(title: str, message: str = ..., input_text: str = ..., ok_button_title: str = ..., hide_cancel_button: bool = ...) -> str: ...

def login_alert(title: str, message: str = ..., login: str = ..., password: str = ..., ok_button_title: str = ...) -> tuple: ...

def password_alert(title: str, message: str = ..., password: str = ..., ok_button_title: str = ...) -> str: ...

def set_color(r: float = ..., g: float = ..., b: float = ...) -> None: ...

def set_font(name: str = ..., size: float = ...) -> None: ...

def clear() -> Any: ...

def write_link(title: str, url: str = ..., font: tuple = ...) -> Any: ...

__all__ = ['alert', 'hud_alert', 'input_alert', 'login_alert', 'password_alert', 'set_color', 'set_font', 'clear', 'write_link']
