"""Type stubs for `contacts` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

PERSON: int

ORGANIZATION: int

class ContactsError:
    def __init__(self, message: Any, code: Any | None = ..., domain: Any | None = ...) -> None: ...

class Person:
    def __init__(self, data: Any | None = ..., is_new: bool = ...) -> None: ...
    @property
    def id(self) -> Any: ...
    @property
    def identifier(self) -> Any: ...
    @property
    def deleted(self) -> Any: ...
    @property
    def image_data(self) -> Any: ...
    @image_data.setter
    def image_data(self, value: Any) -> None: ...
    @property
    def thumbnail_image_data(self) -> Any: ...
    @property
    def vcard(self) -> Any: ...

class Group:
    def __init__(self, name: Any | None = ..., data: Any | None = ..., is_new: bool = ...) -> None: ...
    @property
    def id(self) -> Any: ...
    @property
    def identifier(self) -> Any: ...
    def members(self) -> Any: ...
    def add_member(self, person: Any) -> Any: ...
    def remove_member(self, person: Any) -> None: ...

class Container:
    def __init__(self, data: Any) -> None: ...
    def people(self) -> Any: ...
    def groups(self) -> Any: ...

class PropertySelection:
    def __init__(self, data: Any) -> None: ...

def authorization_status() -> Any: ...

def capabilities() -> Any: ...

def is_authorized() -> bool: ...

def request_access() -> Any: ...

def get_all_people(limit: int = ..., offset: int = ..., container: Any | None = ...) -> Any: ...

def get_person(person_or_id: Any, include_image_data: bool = ..., include_vcard: bool = ...) -> Any: ...

def get_me() -> Any: ...

def find(name: Any) -> Any: ...

def find_by_phone(phone: Any) -> Any: ...

def find_by_email(email: Any) -> Any: ...

def add_person(person: Any | None = ...) -> Any: ...

def remove_person(person: Any) -> None: ...

def save() -> Any: ...

def revert() -> Any: ...

def get_all_groups(container: Any | None = ...) -> Any: ...

def get_group(group_or_id: Any) -> Any: ...

def add_group(group: Any | None = ...) -> Any: ...

def remove_group(group: Any) -> None: ...

def get_all_containers() -> Any: ...

def get_default_container() -> Any: ...

def get_people_in_group(group: Any) -> Any: ...

def get_people_in_container(container: Any) -> Any: ...

def get_groups_in_container(container: Any) -> Any: ...

def pick_contact(multi: bool = ...) -> Any: ...

def pick_contacts() -> Any: ...

def pick_property(kind: str = ..., multi: bool = ...) -> Any: ...

def show_person(person: Any, *, allows_editing: bool = ..., allows_actions: bool = ..., displayed_property_keys: Any | None = ..., property_key: Any | None = ..., property_identifier: Any | None = ..., should_show_linked_contacts: bool = ...) -> Any: ...

def edit_person(person: Any, **kwargs: Any) -> Any: ...

def new_person(seed: Any | None = ..., container: Any | None = ..., group: Any | None = ...) -> Any: ...

def export_vcards(people: Any) -> Any: ...

def import_vcards(data: Any, container: Any | None = ...) -> Any: ...

def get_change_history(token: Any | None = ..., include_group_changes: bool = ..., excluded_transaction_authors: Any | None = ...) -> Any: ...

def manage_limited_access() -> Any: ...

def localized_label(label: Any) -> Any: ...

__all__ = ['PERSON', 'ORGANIZATION', 'ContactsError', 'Person', 'Group', 'Container', 'PropertySelection', 'authorization_status', 'capabilities', 'is_authorized', 'request_access', 'get_all_people', 'get_person', 'get_me', 'find', 'find_by_phone', 'find_by_email', 'add_person', 'remove_person', 'save', 'revert', 'get_all_groups', 'get_group', 'add_group', 'remove_group', 'get_all_containers', 'get_default_container', 'get_people_in_group', 'get_people_in_container', 'get_groups_in_container', 'pick_contact', 'pick_contacts', 'pick_property', 'show_person', 'edit_person', 'new_person', 'export_vcards', 'import_vcards', 'get_change_history', 'manage_limited_access', 'localized_label']
