"""Type stubs for `database` MiniApp native SQLite module."""

from __future__ import annotations

from typing import Any, ContextManager, Dict, List, Optional

class DatabaseError(RuntimeError):
    code: Any
    def __init__(self, message: Any, code: Any = ...) -> None: ...

class Database:
    path: str
    user_version: int
    def __init__(self, name: str = ..., *, timeout: float = ..., pragmas: bool = ...) -> None: ...
    def execute(self, sql: str, params: Any = ...) -> int:
        """Execute SQL. ``bytes``, ``bytearray`` and ``memoryview`` bind as SQLite BLOB values."""
        ...
    def executemany(self, sql: str, seq_of_params: Any) -> int: ...
    def executescript(self, script: str) -> "Database": ...
    def query(self, sql: str, params: Any = ...) -> List[Dict[str, Any]]:
        """Return rows with SQLite BLOB columns decoded as Python ``bytes``."""
        ...
    def query_one(self, sql: str, params: Any = ..., default: Any = ...) -> Optional[Dict[str, Any]]: ...
    def scalar(self, sql: str, params: Any = ..., default: Any = ...) -> Any: ...
    def transaction(self) -> ContextManager["Database"]: ...
    def collection(self, name: str) -> "Collection": ...
    def close(self) -> None: ...

class Collection:
    db: Database
    name: str
    def __init__(self, db: Database, name: str) -> None: ...
    def upsert(self, key: Any, value: Any) -> Any: ...
    def get(self, key: Any, default: Any = ...) -> Any: ...
    def delete(self, key: Any) -> int: ...
    def clear(self) -> int: ...
    def count(self) -> int: ...
    def items(self, order_by: str = ..., limit: Optional[int] = ..., offset: int = ...) -> List[Dict[str, Any]]: ...
    def list(self, order_by: str = ..., limit: Optional[int] = ..., offset: int = ...) -> List[Any]: ...
    def migrate_from_storage(self, storage_key: str, *, key_field: str = ..., remove: bool = ...) -> int: ...

def open(name: str = ..., **kwargs: Any) -> Database: ...
def connect(name: str = ..., **kwargs: Any) -> Database: ...
def default_database() -> Database: ...
def collection(name: str) -> Collection: ...
def database_path(name: str = ...) -> str: ...
def close_default_database() -> None: ...
def close_all() -> None: ...

__all__ = [
    'DatabaseError', 'Database', 'Collection', 'open', 'connect',
    'default_database', 'collection', 'database_path',
    'close_default_database', 'close_all',
]
