"""Type stubs for `device` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def name() -> str: ...

def model() -> str: ...

def system_name() -> str: ...

def system_version() -> str: ...

def identifier_for_vendor() -> str: ...

def battery_level() -> float: ...

def battery_state() -> str: ...

def orientation() -> str: ...

def screen_width() -> float: ...

def screen_height() -> float: ...

def screen_size() -> tuple[float, float]: ...

def screen_scale() -> float: ...

def screen_brightness() -> float: ...

def set_screen_brightness(value: float) -> None: ...

def total_memory() -> int: ...

def processor_count() -> int: ...

def system_uptime() -> float: ...

def thermal_state() -> str: ...

def is_low_power_mode() -> bool: ...

def locale() -> str: ...

def timezone() -> str: ...

def preferred_languages() -> list[str]: ...

__all__ = ['name', 'model', 'system_name', 'system_version', 'identifier_for_vendor', 'battery_level', 'battery_state', 'orientation', 'screen_width', 'screen_height', 'screen_size', 'screen_scale', 'screen_brightness', 'set_screen_brightness', 'total_memory', 'processor_count', 'system_uptime', 'thermal_state', 'is_low_power_mode', 'locale', 'timezone', 'preferred_languages']
