"""Type stubs for `dialogs` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def alert(title: str, message: str = ..., *button_titles: Any, hide_cancel_button: bool = ...) -> int: ...

def input_alert(title: str, message: str = ..., placeholder: str = ..., secure: bool = ..., default_text: str = ...) -> str: ...

def list_dialog(title: str, items: list, multiple: bool = ...) -> Any: ...

def form_dialog(title: str, fields: list) -> dict: ...

def date_dialog(title: str = ..., mode: str = ...) -> str: ...

def hud_alert(message: str, duration: float = ...) -> None: ...

class editor:
    @staticmethod
    def get_path() -> str: ...
    @staticmethod
    def get_text() -> str: ...
    @staticmethod
    def replace_text(start: int, end: int, replacement: str) -> None: ...
    @staticmethod
    def get_selection() -> tuple: ...
    @staticmethod
    def set_selection(start: int, end: int = ...) -> None: ...
    @staticmethod
    def make_new_file(name: str = ..., text: str = ...) -> None: ...

__all__ = ['alert', 'input_alert', 'list_dialog', 'form_dialog', 'date_dialog', 'hud_alert', 'editor']
