"""Type stubs for `haptics` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def impact(style: str = ..., intensity: float = ...) -> None: ...

def notification(type: str = ...) -> None: ...

def selection() -> None: ...

def success() -> None: ...

def warning() -> None: ...

def error() -> None: ...

def light() -> None: ...

def medium() -> None: ...

def heavy() -> None: ...

def is_supported() -> bool: ...

def play(events: list[dict[str, Any]]) -> bool: ...

def stop() -> None: ...

__all__ = [
    'impact', 'notification', 'selection',
    'success', 'warning', 'error', 'light', 'medium', 'heavy',
    'is_supported', 'play', 'stop',
]
