"""Type stubs for `health` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def is_available() -> bool: ...

def request_authorization(read: Sequence[str] | str | None = ..., write: Sequence[str] | str | None = ...) -> bool: ...

def authorization_status(type_id: str) -> str: ...

def query_steps(start: Any | None = ..., end: Any | None = ...) -> Any: ...

def query_heart_rate(start: Any | None = ..., end: Any | None = ...) -> Any: ...

def query_weight(limit: int = ...) -> Any: ...

def save_weight(kg: Any, timestamp: Any | None = ...) -> Any: ...

def query_workouts(limit: int = ...) -> Any: ...

def query_sleep(start: Any | None = ..., end: Any | None = ...) -> Any: ...

def query_quantity(type_id: Any, start: Any | None = ..., end: Any | None = ..., unit: str = ...) -> Any: ...

def query_blood_pressure(start: Any | None = ..., end: Any | None = ...) -> Any: ...

def summarize_blood_pressure(records: Any | None = ..., start: Any | None = ..., end: Any | None = ...) -> Any: ...

__all__ = ['is_available', 'request_authorization', 'authorization_status', 'query_steps', 'query_heart_rate', 'query_weight', 'save_weight', 'query_workouts', 'query_sleep', 'query_quantity', 'query_blood_pressure', 'summarize_blood_pressure']
