"""Type stubs for `keyboard` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def add_button(label: Any, action: Callable[..., Any] | None = ..., icon: Any | None = ...) -> Any: ...

def add_group(name: Any, buttons: Any) -> Any: ...

def remove_button(label: Any) -> None: ...

def clear() -> Any: ...

def insert_text(text: Any, offset: int = ...) -> Any: ...

def insert_snippet(template: Any) -> Any: ...

def move_cursor(offset: Any) -> Any: ...

class Button:
    def __init__(self, label: Any, action: Callable[..., Any] | None = ..., icon: Any | None = ...) -> None: ...
    def to_dict(self) -> Any: ...

def set_buttons(buttons: Any) -> None: ...

__all__ = ['add_button', 'add_group', 'remove_button', 'clear', 'insert_text', 'insert_snippet', 'move_cursor', 'Button', 'set_buttons']
