"""Type stubs for `location` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def authorization_status() -> Any: ...

def is_authorized() -> bool: ...

def request_access() -> Any: ...

def start_updates() -> Any: ...

def stop_updates() -> None: ...

def get_location() -> Any: ...

def start_heading() -> Any: ...

def stop_heading() -> None: ...

def get_heading() -> Any: ...

def reverse_geocode(latitude: Any, longitude: Any) -> Any: ...

def geocode(address: Any) -> Any: ...

__all__ = ['authorization_status', 'is_authorized', 'request_access', 'start_updates', 'stop_updates', 'get_location', 'start_heading', 'stop_heading', 'get_heading', 'reverse_geocode', 'geocode']
