from typing import IO, Any, Dict, Iterator, List, Mapping, Optional, Tuple

class LaunchRequestError(RuntimeError): ...

class LaunchItem(Mapping[str, Any]):
    @property
    def id(self) -> str: ...
    @property
    def kind(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def content_type(self) -> str: ...
    @property
    def size(self) -> int: ...
    @property
    def path(self) -> str: ...
    @property
    def url(self) -> Optional[str]: ...
    def open(
        self,
        mode: str = ...,
        *,
        encoding: str = ...,
        errors: str = ...,
    ) -> IO[Any]: ...
    def read_bytes(self, max_bytes: int = ...) -> bytes: ...
    def read_text(
        self,
        encoding: str = ...,
        errors: str = ...,
        max_bytes: int = ...,
    ) -> str: ...

class LaunchRequest(Mapping[str, Any]):
    @property
    def id(self) -> str: ...
    @property
    def source(self) -> str: ...
    @property
    def created_at(self) -> float: ...
    @property
    def target_miniapp_id(self) -> str: ...
    @property
    def items(self) -> Tuple[LaunchItem, ...]: ...
    @property
    def first(self) -> Optional[LaunchItem]: ...
    @property
    def files(self) -> Tuple[str, ...]: ...
    @property
    def urls(self) -> Tuple[str, ...]: ...

def launch_request(required: bool = ...) -> Optional[LaunchRequest]: ...
def has_launch_request() -> bool: ...
def durable_tasks(
    *,
    kind: Optional[str] = ...,
    state: Optional[str] = ...,
    limit: int = ...,
) -> List[Dict[str, Any]]: ...
def durable_task(task_id: str) -> Dict[str, Any]: ...
def health_config() -> Mapping[str, Any]: ...
def is_health_request(path: str, headers: Optional[Mapping[str, str]] = ...) -> bool: ...
def health_payload() -> Mapping[str, Any]: ...
def health_headers() -> Mapping[str, str]: ...
def health_response() -> Tuple[str, int, Mapping[str, str]]: ...

__all__ = [
    "LaunchItem",
    "LaunchRequest",
    "LaunchRequestError",
    "launch_request",
    "has_launch_request",
    "durable_tasks",
    "durable_task",
    "health_config",
    "is_health_request",
    "health_payload",
    "health_headers",
    "health_response",
]
