"""Type stubs for `motion` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def is_available() -> bool: ...

def start_updates(interval: int = ...) -> Any: ...

def stop_updates() -> None: ...

def start_accelerometer(interval: int = ...) -> Any: ...

def stop_accelerometer() -> None: ...

def start_gyroscope(interval: int = ...) -> Any: ...

def stop_gyroscope() -> None: ...

def start_magnetometer(interval: int = ...) -> Any: ...

def stop_magnetometer() -> None: ...

def start_altimeter() -> Any: ...

def stop_altimeter() -> None: ...

def get_acceleration() -> Any: ...

def get_gravity() -> Any: ...

def get_rotation_rate() -> Any: ...

def get_magnetic_field() -> Any: ...

def get_attitude() -> Any: ...

def get_altitude() -> Any: ...

__all__ = ['is_available', 'start_updates', 'stop_updates', 'start_accelerometer', 'stop_accelerometer', 'start_gyroscope', 'stop_gyroscope', 'start_magnetometer', 'stop_magnetometer', 'start_altimeter', 'stop_altimeter', 'get_acceleration', 'get_gravity', 'get_rotation_rate', 'get_magnetic_field', 'get_attitude', 'get_altitude']
