"""Type stubs for `network` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def is_connected() -> bool: ...

def connection_type() -> str: ...

def is_expensive() -> bool: ...

def is_constrained() -> bool: ...

def request(method: str, url: str, *, headers: dict[str, str] | None = ..., body: str | bytes | None = ..., json: Any | None = ..., timeout: float = ...) -> Response: ...

def get(url: str, **kwargs: Any) -> Response: ...

def post(url: str, **kwargs: Any) -> Response: ...

def put(url: str, **kwargs: Any) -> Response: ...

def delete(url: str, **kwargs: Any) -> Response: ...

def patch(url: str, **kwargs: Any) -> Response: ...

def stream(method: str, url: str, *, headers: dict[str, str] | None = ..., body: str | bytes | bytearray | memoryview | None = ..., json: Any | None = ..., timeout: float = ..., read_timeout: float = ..., buffer_limit: int = ...) -> StreamResponse: ...

def download(url: str, dest_path: str, timeout: float = ...) -> bool: ...

class Response:
    status: Any
    body: Any
    headers_raw: Any
    def __init__(self, status: Any, body: Any, headers_raw: Any) -> None: ...
    @property
    def ok(self) -> bool: ...
    @property
    def text(self) -> str: ...
    def json(self) -> Any: ...
    @property
    def headers(self) -> dict[str, str]: ...

class StreamError(RuntimeError):
    code: str | None
    def __init__(self, message: str, code: str | None = ...) -> None: ...

class StreamResponse:
    status: int
    headers: dict[str, str]
    url: str
    @property
    def ok(self) -> bool: ...
    @property
    def closed(self) -> bool: ...
    def iter_bytes(self, chunk_size: int = ..., timeout: float | None = ...) -> Iterable[bytes]: ...
    def iter_text(self, encoding: str = ..., errors: str = ..., chunk_size: int = ..., timeout: float | None = ...) -> Iterable[str]: ...
    def iter_lines(self, encoding: str = ..., errors: str = ..., chunk_size: int = ..., timeout: float | None = ..., max_line_chars: int = ...) -> Iterable[str]: ...
    def iter_sse(self, encoding: str = ..., errors: str = ..., timeout: float | None = ..., max_event_chars: int = ...) -> Iterable[dict[str, Any]]: ...
    def read(self, max_bytes: int = ..., chunk_size: int = ..., timeout: float | None = ...) -> bytes: ...
    def json(self, encoding: str = ..., max_bytes: int = ..., timeout: float | None = ...) -> Any: ...
    def close(self) -> None: ...
    def cancel(self) -> None: ...
    def __enter__(self) -> "StreamResponse": ...
    def __exit__(self, exc_type: Any, exc: Any, tb: Any) -> bool: ...

__all__ = ['is_connected', 'connection_type', 'is_expensive', 'is_constrained', 'request', 'get', 'post', 'put', 'delete', 'patch', 'stream', 'download', 'Response', 'StreamResponse', 'StreamError']
