"""Type stubs for `notification` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def request_permission() -> Any: ...

def authorization_status() -> Any: ...

def schedule(identifier: Any, title: Any, body: Any, delay: float = ..., sound: bool = ..., badge: int = ...) -> Any: ...

def schedule_at_date(identifier: Any, title: Any, body: Any, year: Any, month: Any, day: Any, *, hour: int = ..., minute: int = ..., sound: bool = ..., badge: int = ..., repeats: bool = ...) -> Any: ...

def remove_pending(identifier: Any) -> None: ...

def remove_all_pending() -> None: ...

def pending_count() -> Any: ...

def pending_identifiers() -> Any: ...

def set_badge(number: Any) -> None: ...

__all__ = ['request_permission', 'authorization_status', 'schedule', 'schedule_at_date', 'remove_pending', 'remove_all_pending', 'pending_count', 'pending_identifiers', 'set_badge']
