"""Type stubs for `photos` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def pick_image(show_albums: bool = ..., include_metadata: bool = ..., original: bool = ..., raw_data: bool = ..., multi: bool = ..., **kwargs: Any) -> Any: ...

def capture_image(camera: str = ..., show_preview: bool = ..., flash: str = ..., **kwargs: Any) -> Any: ...

def save_image(image: Any, format: str = ..., quality: float = ..., album_name: Any | None = ..., **kwargs: Any) -> Any: ...

def save_video(path: str, album_name: Any | None = ..., **kwargs: Any) -> bool: ...

def get_assets(media_type: str = ..., limit: int = ..., **kwargs: Any) -> Any: ...

def pick_asset(assets: Any | None = ..., title: Any | None = ..., multi: bool = ..., **kwargs: Any) -> Any: ...

def get_image(asset: Any, original: bool = ...) -> Any: ...

class Asset:
    def __init__(self, info_dict: Any) -> None: ...
    @property
    def local_identifier(self) -> Any: ...
    @property
    def media_type(self) -> Any: ...
    @property
    def pixel_width(self) -> Any: ...
    @property
    def pixel_height(self) -> Any: ...
    @property
    def creation_date(self) -> Any: ...
    @property
    def modification_date(self) -> Any: ...
    @property
    def location(self) -> Any: ...
    @property
    def duration(self) -> Any: ...
    @property
    def is_favorite(self) -> bool: ...
    def get_image(self, original: bool = ..., raw_data: bool = ...) -> Any: ...
    def get_ui_image(self, original: bool = ...) -> Any: ...

class AssetCollection:
    def __init__(self, title: Any, identifier: Any | None = ..., count: int = ..., collection_type: str = ...) -> None: ...
    @property
    def count(self) -> Any: ...
    def get_assets(self) -> Any: ...

def get_albums() -> Any: ...

def get_smart_albums() -> Any: ...

def get_moments() -> Any: ...

def create_album(title: Any) -> Any: ...

def get_screenshots_album() -> Any: ...

def get_recently_added_album() -> Any: ...

def get_selfies_album() -> Any: ...

def pick_image_base64(format: str = ..., quality: float = ...) -> Any: ...

def capture_image_base64(format: str = ..., quality: float = ...) -> Any: ...

def image_to_base64(image: Any, format: str = ..., quality: float = ...) -> Any: ...

def base64_to_image(b64_string: Any) -> Any: ...

def get_favorites() -> Any: ...

def get_count(media_type: str = ...) -> Any: ...

def get_recent_images(count: int = ...) -> Any: ...

def get_image_size(image: Any) -> Any: ...

def get_metadata(image: Any) -> Any: ...

def is_available() -> bool: ...

__all__ = ['pick_image', 'capture_image', 'save_image', 'save_video', 'get_assets', 'pick_asset', 'get_image', 'Asset', 'AssetCollection', 'get_albums', 'get_smart_albums', 'get_moments', 'create_album', 'get_screenshots_album', 'get_recently_added_album', 'get_selfies_album', 'pick_image_base64', 'capture_image_base64', 'image_to_base64', 'base64_to_image', 'get_favorites', 'get_count', 'get_recent_images', 'get_image_size', 'get_metadata', 'is_available']
