"""Type stubs for `sound` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def play_effect(name: str, volume: float = ..., pitch: float = ..., pan: float = ..., looping: bool = ...) -> Any: ...

def stop_effect(effect_handle: Any) -> None: ...

def stop_all_effects() -> None: ...

class Player:
    def __init__(self, file_path: str = ...) -> None: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    @property
    def playing(self) -> bool: ...
    @property
    def duration(self) -> float: ...
    @property
    def current_time(self) -> float: ...
    @current_time.setter
    def current_time(self, value: float) -> None: ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, value: float) -> None: ...
    @property
    def rate(self) -> float: ...
    @rate.setter
    def rate(self, value: float) -> None: ...
    @property
    def number_of_loops(self) -> int: ...
    @number_of_loops.setter
    def number_of_loops(self, value: int) -> None: ...
    @property
    def file_path(self) -> str: ...

class MIDIPlayer:
    def __init__(self, file_path: str = ..., sound_bank_path: str = ...) -> None: ...
    def play(self) -> None: ...
    def stop(self) -> None: ...
    def pause(self) -> None: ...
    @property
    def playing(self) -> bool: ...

def set_volume(volume: float) -> None: ...

def set_honors_silent_switch(flag: bool) -> None: ...

def get_volume() -> float: ...

__all__ = ['play_effect', 'stop_effect', 'stop_all_effects', 'Player', 'MIDIPlayer', 'set_volume', 'set_honors_silent_switch', 'get_volume']
