"""Type stubs for `storage` public PythonIDE module."""

from __future__ import annotations

from typing import Any

class SharedStorage:
    """Explicit app-wide storage shared by authorized scripts and MiniApps."""

    def get(self, key: str, default: Any | None = ...) -> str | Any | None: ...
    def set(self, key: str, value: Any) -> None: ...
    def get_int(self, key: str, default: int = ...) -> int: ...
    def set_int(self, key: str, value: int) -> None: ...
    def get_float(self, key: str, default: float = ...) -> float: ...
    def set_float(self, key: str, value: float) -> None: ...
    def get_bool(self, key: str, default: bool = ...) -> bool: ...
    def set_bool(self, key: str, value: bool) -> None: ...
    def get_json(self, key: str, default: Any | None = ...) -> Any: ...
    def set_json(self, key: str, value: Any) -> None: ...
    def remove(self, key: str) -> None: ...
    def has_key(self, key: str) -> bool: ...
    def all_keys(self, prefix: str = ...) -> list[str]: ...

def get(key: str, default: Any | None = ...) -> str | Any | None: ...

def set(key: str, value: Any) -> None: ...

def get_int(key: str, default: int = ...) -> int: ...

def set_int(key: str, value: int) -> None: ...

def get_float(key: str, default: float = ...) -> float: ...

def set_float(key: str, value: float) -> None: ...

def get_bool(key: str, default: bool = ...) -> bool: ...

def set_bool(key: str, value: bool) -> None: ...

def get_json(key: str, default: Any | None = ...) -> Any: ...

def set_json(key: str, value: Any) -> None: ...

def remove(key: str) -> None: ...

def has_key(key: str) -> bool: ...

def all_keys(prefix: str = ...) -> list[str]: ...

shared: SharedStorage

__all__ = ['get', 'set', 'get_int', 'set_int', 'get_float', 'set_float', 'get_bool', 'set_bool', 'get_json', 'set_json', 'remove', 'has_key', 'all_keys', 'shared']
