"""Type stubs for `vision_helper` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def setup_vision_framework() -> Any: ...

def is_vision_available() -> bool: ...

def detect_faces(image_base64: Any) -> Any: ...

def detect_face_landmarks(image_base64: Any) -> Any: ...

def detect_barcodes(image_base64: Any) -> Any: ...

def classify_image(image_base64: Any, max_results: int = ...) -> Any: ...

def detect_rectangles(image_base64: Any) -> Any: ...

def async_request(operation: Any, image_base64: Any, callback_id: Any, extra: int = ...) -> Any: ...

def poll_result(callback_id: Any) -> Any: ...

__all__ = ['setup_vision_framework', 'is_vision_available', 'detect_faces', 'detect_face_landmarks', 'detect_barcodes', 'classify_image', 'detect_rectangles', 'async_request', 'poll_result']
