"""Type stubs for `websocket` public PythonIDE module."""

from __future__ import annotations

from typing import Any, Callable, Dict, Iterable, List, Mapping, Optional, Sequence, Tuple, Union

def connect(url: Any, protocols: Any | None = ...) -> Any: ...

class WebSocket:
    def __init__(self, conn_id: Any) -> None: ...
    @property
    def state(self) -> Any: ...
    @property
    def is_open(self) -> bool: ...
    def send(self, data: Any) -> Any: ...
    def receive(self, timeout: int = ...) -> Any: ...
    def close(self, code: int = ...) -> Any: ...
    @property
    def on_message(self) -> Any: ...
    @on_message.setter
    def on_message(self, callback: Callable[..., Any]) -> None: ...
    @property
    def on_close(self) -> Any: ...
    @on_close.setter
    def on_close(self, callback: Callable[..., Any]) -> None: ...
    @property
    def on_error(self) -> Any: ...
    @on_error.setter
    def on_error(self, callback: Callable[..., Any]) -> None: ...
    @property
    def on_open(self) -> Any: ...
    @on_open.setter
    def on_open(self, callback: Callable[..., Any]) -> None: ...

__all__ = ['connect', 'WebSocket']
